### ISSUE TITLE
NCDslTokenQualifier error

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#215]
try sentence "Utah , Texas"  - branch GH-200, model sql.model.id

Jan-31|17:47:41|ERROR| Failed to process request.
java.lang.IllegalArgumentException: Unknown part token qualifier: col
	at org.nlpcraft.model.intent.utils.NCDslTokenQualifier$$anonfun$2$$anonfun$apply$1.apply(NCDslTokenQualifier.scala:65) ~[classes/:?]
	at org.nlpcraft.model.intent.utils.NCDslTokenQualifier$$anonfun$2$$anonfun$apply$1.apply(NCDslTokenQualifier.scala:51) ~[classes/:?]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[scala-library-2.11.1.jar:?]

**Comment by vic64** [comment]
Fixed in `release`. Please test it on your stuff (tested locally).

**Comment by skhdl** [comment]
It still doesn't work for some sentences (for given sentence works fine)
 -  GH-200
 - start server and probe
 - test org.nlpcraft.examples.nlp2sql.Nlp2SqlTest
 - See probe stack

**Comment by vic64** [comment]
Let's discuss.

**Comment by skhdl** [comment]
ready for review GH-215 (already merged into GH-200)
